/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmspilmanbridge_free: (a: number, b: number) => void;
export const channel_parameters_get_channel_id: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const compute_channel_secret: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const compute_funding_token_amount: (a: bigint, b: number, c: number, d: bigint) => [bigint, number, number];
export const compute_funding_token_nominal: (a: bigint, b: number, c: number, d: bigint) => [bigint, number, number];
export const construct_proofs: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const create_funding_outputs: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const get_receiver_blinded_secret_key_for_stage2_output: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: bigint, j: number) => [number, number, number, number];
export const get_sender_blinded_secret_key_for_stage2_output: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint, h: number) => [number, number, number, number];
export const sign_with_tweaked_key: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const spilman_channel_sender_create_signed_balance_update: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: bigint) => [number, number, number, number];
export const unblind_and_verify_dleq: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: bigint, l: number, m: number) => [number, number, number, number];
export const verify_balance_update_signature: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: bigint, l: number, m: number) => [number, number, number];
export const verify_channel: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const verify_proof_dleq: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasmspilmanbridge_createUnilateralCloseData: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmspilmanbridge_executeCooperativeClose: (a: number, b: number, c: number) => any;
export const wasmspilmanbridge_executeUnilateralClose: (a: number, b: number, c: number) => any;
export const wasmspilmanbridge_fundChannel: (a: number, b: number, c: number) => [number, number, number];
export const wasmspilmanbridge_processPayment: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmspilmanbridge_validateAndPrepareCooperativeClose: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmspilmanbridge_validatePayment: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmspilmanbridge_new: (a: any) => number;
export const init: () => void;
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h57799704a46dd3be: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h4dc10dde27f91a71: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h774e692e0dfc3d08: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
